const REQUEST_AUTH = 'REQUEST_AUTH'
const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
const REQUEST_REFRESH_TOKEN = 'REQUEST_REFRESH_TOKEN'
const REQUEST_PROFILE_ID = 'REQUEST_PROFILE_ID'

export {
  REQUEST_AUTH,
  REQUEST_LOGOUT,
  REQUEST_REFRESH_TOKEN,
  REQUEST_PROFILE_ID
}